import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/store/provider";
import AppWalletProvider from "@/sol-store/appwalletprovider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={''}>
       <AppWalletProvider>
       <ReduxProvider>
          {children}
       </ReduxProvider>
       </AppWalletProvider>
      </body>
    </html>
  );
}
