import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/store/provider";
import AppWalletProvider from "./components/AppWalletProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={""}>
        <ReduxProvider>
          <AppWalletProvider>{children}</AppWalletProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
